version: '3.8'

services:
  mysql:
        image: arm64v8/mysql:8.0.29
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080


  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

