FROM node:18.19.1-alpine3.19

WORKDIR /app

COPY package*.json .
COPY yarn.lock .

RUN yarn install 

COPY . .

RUN rm .yarnrc

RUN yarn nx --skip-nx-cache build app-sync-hubspot

ENTRYPOINT ["yarn" "nx" "--skip-nx-cache" "run"]